x-api-template: &api-template
    build:
      context: .
      dockerfile: Dockerfile.api
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "120MB"

services:
  api1:
    <<: *api-template
    container_name: api1
    depends_on:
      - health
      - redis

  api2:
    <<: *api-template
    container_name: api2
    depends_on:
      - health
      - redis

  health:
    build:
      context: .
      dockerfile: Dockerfile.health
    container_name: health
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"

  redis:
    image: redis:7-alpine
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

  haproxy:
    image: haproxy:3.2.3-alpine
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:80"
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "70MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

