FROM golang:1.24.5-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 \
    go build -ldflags='-w -s' -a -installsuffix cgo \
    -gcflags='-m=2' -o health ./cmd/health/main.go

FROM scratch
COPY --from=builder /app/health /health
ENTRYPOINT ["/health"]