version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 9999:8080 
    sysctls:
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.tcp_fin_timeout=15
    networks:
      - backend
      - payment-processor

  health:
    build:
      context: .
      dockerfile: Dockerfile.health
    container_name: health
    networks:
      - backend
      - payment-processor

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - backend


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

